def end1():
    s1 = ("You immeditaly go back to Crystal's body to see if she was wearing any buttoned up shirt.")
    print(s1)
    input()
    s2 = ("Henry : 'Could you stop being weird, She's dead so stop disrespecting her body. Let her be.")
    print(s2)
    input()
    s3 = ("You : 'I think I found who did it but you guys have to keep it a secret'")
    print(s3)
    input()
    s4 = ("You : 'Adrian, could you call the cops now, we just have to lock the doors and keep everyone in awhile'")
    print(s4)
    input()
    s5 = ("You wait for the cops to arrive and when they do, everyone is very confused at the scene. You are approached by a cop while they ask you a question")
    print(s5)
    input()
    s6 = ("Cop : 'Did you see or know anybody who would do this Crime?'")
    print(s6)
    input()
    s7 = ("You tell him it might've been Matthew due to him holding Crystal's personal thing")
    print(s7)
    input()
    s8 = ("After a few days of the incident, it has been found that Matthew was guitly of taking Crystal's life over a relationship reason they had back then")
    print(s8)
    input()
    print("\n\n\n\n\n")
    print("CREDITS")
    print("Thank you for playing this very short game. Due to the time limit of this project, there were only two choices of picking the right answer. Hope you enjoyed playing this game")
    input()


    
